version: "3"

services:
  traefik:
    build:
      context: .
      dockerfile: Traefik.Production.Dockerfile
    ports:
      - 443:443
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-public-certificates:/certificates"
    networks:
      - traefik_webgateway
    restart: always

networks:
  traefik_webgateway:
    external: true

volumes:
  traefik-public-certificates: